include stdint.h and cstdint explicitly for newer gcc versions
Never c/c++ header versions provided by the gcc 15
requires that stdint.h and cstdint needs to be included excplicitly
to avoid build errors related to types like uint32_t.

Fixes following type of errors:

/therock/rocm-systems/projects/rocprofiler-systems/external/dyninst/common/src/sha1.C:112:5:
error: ‘uint32_t’ does not name a type
10.6      112 |     uint32_t state[5];

and

‘INT32_MAX’ was not declared in this scope

Signed-off-by: Mika Laitio <mika.laitio@amd.com>